### Post request to auth register
@host = http://localhost:8080


POST {{host}}/api/auth/sign-up
Content-Type: application/json

{
  "username": "daniel",
  "password": "daniel"
}
### POST request sign in
POST {{host}}/api/auth/sign-in
Content-Type: application/json

{
  "username": "daniel",
  "password": "daniel"
}

### POST logout
POST {{host}}/api/auth/sign-out
Content-Type: application/json


### GET user/me
GET {{host}}/api/user/me
Content-Type: application/json


### GET resource?path=
GET {{host}}/resource?path=sosal1/
Content-Type: application/json


### DELETE resource?path=
DELETE {{host}}/resource?path=xui/sosat/
Content-Type: application/json


### POST directory?path=
POST {{host}}/directory?path=1234/1234/
Content-Type: application/json


### GET directory?path=
GET {{host}}/directory?path=1234/
Content-Type: application/json

### GET /resource/download
GET {{host}}/resource/download?path=1234/
Content-Type: application/json


### GET /resource/move
GET {{host}}/resource/move?from=123/tuda.png&to=tuda.png
Content-Type: application/json

### GET /resource/move
GET {{host}}/resource/move?from=1234/&to=1234/1234/
Content-Type: application/json



###
# curl --request POST
#  --url 'http://localhost:8080/resource?path=sosal1%2F'
#  --header 'Content-Type: multipart/form-data'
#  --header 'User-Agent: insomnia/12.3.0'
#  --cookie JSESSIONID=6DE29115FE4C5C7254261F3778388BBA
#  --form files=@/Users/daniil/Desktop/sosal123/tuda.png
POST http://localhost:8080/resource?path=sosal1%2F
User-Agent: insomnia/12.3.0
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="sosal123/tuda.png"

#< /Users/daniil/Desktop/sosal123/tuda.png
files=@/Users/daniil/Desktop/sosal123/tuda.png
--WebAppBoundary--

###

