### Post request to auth register
@host = http://localhost:8080


POST {{host}}/api/auth/sign-up
Content-Type: application/json

{
  "username": "daniel",
  "password": "daniel"
}
### POST request sign in
POST {{host}}/api/auth/sign-in
Content-Type: application/json

{
  "username": "daniel",
  "password": "daniel"
}

### POST logout
POST {{host}}/api/auth/sign-out
Content-Type: application/json


### GET user/me
GET {{host}}/api/user/me
Content-Type: application/json


### GET resource?path=
GET {{host}}/resource?path=sosal/1
Content-Type: application/json


### DELETE resource?path=
DELETE {{host}}/resource?path=sosal/
Content-Type: application/json

